# Form implementation generated from reading ui file 'untitled4.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QMessageBox
import numpy as np
from scipy import stats

### 双样本 t 检验
class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 586)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(220, 20, 131, 16))
        self.radioButton.setStyleSheet("font: 8pt \"Agency FB\";\n"
                                       "font: 8pt \"宋体\";")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(220, 120, 141, 16))
        self.radioButton_2.setStyleSheet("font: 8pt \"Agency FB\";\n"
                                         "font: 8pt \"宋体\";")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(220, 220, 86, 16))
        self.radioButton_3.setStyleSheet("font: 10pt \"Agency FB\";\n"
                                         "font: 8pt \"宋体\";")
        self.radioButton_3.setObjectName("radioButton_3")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(220, 330, 101, 16))
        self.checkBox.setStyleSheet("font: 8pt \"宋体\";")
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 50, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 90, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 150, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 190, 54, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 250, 54, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(240, 300, 54, 12))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(300, 240, 54, 12))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(390, 240, 54, 12))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(480, 240, 54, 12))
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 500, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 530, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 530, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 530, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(60, 480, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.listView_11 = QtWidgets.QListView(parent=self.centralwidget)
        self.listView_11.setGeometry(QtCore.QRect(20, 20, 171, 421))
        self.listView_11.setObjectName("listView_11")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(290, 40, 101, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(290, 80, 101, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(290, 140, 101, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(290, 180, 101, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_10 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_10.setGeometry(QtCore.QRect(390, 250, 71, 31))
        self.textEdit_10.setObjectName("textEdit_10")
        self.textEdit_11 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_11.setGeometry(QtCore.QRect(480, 290, 71, 31))
        self.textEdit_11.setObjectName("textEdit_11")
        self.textEdit_12 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_12.setGeometry(QtCore.QRect(480, 250, 71, 31))
        self.textEdit_12.setObjectName("textEdit_12")
        self.textEdit_13 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_13.setGeometry(QtCore.QRect(390, 290, 71, 31))
        self.textEdit_13.setObjectName("textEdit_13")
        self.textEdit_14 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_14.setGeometry(QtCore.QRect(300, 290, 71, 31))
        self.textEdit_14.setObjectName("textEdit_14")
        self.textEdit_15 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_15.setGeometry(QtCore.QRect(300, 250, 71, 31))
        self.textEdit_15.setObjectName("textEdit_15")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(220, 360, 41, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(240, 380, 61, 16))
        self.label_11.setStyleSheet("font: 8pt \"宋体\";")
        self.label_11.setObjectName("label_11")
        self.textEdit_6 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(310, 370, 101, 31))
        self.textEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_5 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(310, 410, 101, 31))
        self.textEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(240, 420, 61, 16))
        self.label_12.setStyleSheet("font: 8pt \"宋体\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(240, 460, 61, 16))
        self.label_13.setStyleSheet("font: 8pt \"宋体\";")
        self.label_13.setObjectName("label_13")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(310, 450, 101, 31))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.radioButton.raise_()
        self.radioButton_2.raise_()
        self.radioButton_3.raise_()
        self.checkBox.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.pushButton.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.listView_11.raise_()
        self.textEdit.raise_()
        self.textEdit_2.raise_()
        self.textEdit_3.raise_()
        self.textEdit_4.raise_()
        self.textEdit_10.raise_()
        self.textEdit_11.raise_()
        self.textEdit_12.raise_()
        self.textEdit_13.raise_()
        self.textEdit_14.raise_()
        self.textEdit_15.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.textEdit_6.raise_()
        self.textEdit_5.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.comboBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_3.clicked.connect(MainWindow.close)  # type: ignore
        self.pushButton_6.clicked.connect(self.add_selected_column_to_textedit)  # 连接按钮点击事件
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #添加按钮点击事件
        self.radioButton.clicked.connect(self.handle_radio1_click)
        #self.radioButton_2.clicked.connect(self.handle_radio2_click)
        self.radioButton_3.clicked.connect(self.handle_radio3_click)
        self.pushButton_4.clicked.connect(self.on_confirm_button_click)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton.setText(_translate("MainWindow", "样本在一列中(N)"))
        self.radioButton_2.setText(_translate("MainWindow", "样本在不同列中(D):"))
        self.radioButton_3.setText(_translate("MainWindow", "汇总数据(Z)"))
        self.checkBox.setText(_translate("MainWindow", "假定等方差(E)"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" font-size:8pt;\">样本(M):</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:8pt;\">下标(U):</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:8pt;\">第一(F):</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:8pt;\">第二(S):</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:8pt;\">第一(F):</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow",
                                        "<html><head/><body><p><span style=\" font-size:8pt;\">第二(S):</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "样本数量"))
        self.label_8.setText(_translate("MainWindow", "均值"))
        self.label_9.setText(_translate("MainWindow", "标准差"))
        self.pushButton.setText(_translate("MainWindow", "图形(R)..."))
        self.pushButton_3.setText(_translate("MainWindow", "取消"))
        self.pushButton_4.setText(_translate("MainWindow", "确定(O)"))
        self.pushButton_5.setText(_translate("MainWindow", "帮助"))
        self.pushButton_6.setText(_translate("MainWindow", "选择"))
        self.label_10.setText(_translate("MainWindow",
                                         "<html><head/><body><p><span style=\" font-size:8pt; font-weight:600; color:#545454;\">选项</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "置信水平(C):"))
        self.label_12.setText(_translate("MainWindow", "检验差值(T):"))
        self.label_13.setText(_translate("MainWindow", "备择(A):"))
        self.comboBox.setItemText(0, _translate("MainWindow", "小于"))
        self.comboBox.setItemText(1, _translate("MainWindow", "不等于"))
        self.comboBox.setItemText(2, _translate("MainWindow", "大于"))
        self.textEdit_6.setPlainText("95.0")  # 置信水平默认值
        self.textEdit_5.setPlainText("0.0")  # 检验差值默认值

    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window
        self.all_table_data = []  # 用于存储所有表格数据
        self.setupUi(self)
        self.get_table_data()
        self.target_text_edit = None  # 新增属性，用于存储目标文本框

        # 为每个文本框添加鼠标点击事件，点击时设置目标文本框
        text_edits = [self.textEdit, self.textEdit_2, self.textEdit_3, self.textEdit_4]
        for text_edit in text_edits:
            text_edit.mousePressEvent = lambda event, te=text_edit: self.set_target_text_edit(te)

    def set_target_text_edit(self, text_edit):
        self.target_text_edit = text_edit

    def get_table_data(self):
        table = self.main_window.tableWidget
        rows = table.rowCount()
        columns = table.columnCount()
        print(f"表格行数: {rows}, 列数: {columns}")  # 添加调试信息

        data = []
        for row in range(rows):
            row_data = []
            for col in range(columns):
                item = table.item(row, col)
                if item is not None:
                    row_data.append(item.text())
                else:
                    row_data.append(None)
            data.append(row_data)
        print("获取到的主窗口表格数据:", data)

        # 筛选出有数据的列
        valid_columns = []
        for col in range(columns):
            has_data = False
            for row in range(rows):
                if data[row][col] is not None and data[row][col].strip():
                    has_data = True
                    break
            if has_data:
                valid_columns.append(col)

        # 生成列名
        column_names = [f"c{i + 1}" for i in valid_columns]

        # 创建模型并设置数据
        model = QtGui.QStandardItemModel()
        for name in column_names:
            item = QtGui.QStandardItem(name)
            model.appendRow(item)

        # 将模型设置给 listView_11
        self.listView_11.setModel(model)
        self.all_table_data = data  # 保存所有表格数据

    def add_selected_column_to_textedit(self):
        """进行数据的选定"""
        # 获取列表视图中选中的索引
        selected_indexes = self.listView_11.selectedIndexes()

        # 检查是否有选中的列
        if not selected_indexes:
            print("请先在列列表中选择要添加的列名")
            return

        # 获取选中的列名（取第一个选中项）
        selected_item = selected_indexes[0].data()
        print(f"已选择列名: {selected_item}")

        # 检查目标文本框是否已指定（通过点击文本框初始化）
        if not hasattr(self, 'target_text_edit') or self.target_text_edit is None:
            print("错误：未指定目标文本框，请先点击需要添加列名的文本框")
            return

        # 直接覆盖文本框内容（确保始终只保留最后选择的列名）
        self.target_text_edit.setText(selected_item)
        print(f"列名已更新到目标文本框: {selected_item}")

        # 方法 1：对应 radioButton 点击
    def handle_radio1_click(self):
            """ 样本在同一列"""
            if self.radioButton.isChecked():
                # 执行 radioButton 对应的逻辑
                print("RadioButton 1 被选中")
                # 这里添加具体功能代码

        # 方法 2：对应 radioButton_2 点击
    def handle_radio2_click(self):
        """样本在不同列"""
        print("【handle_radio2_click】开始执行")

        # 获取文本框中的列名
        column_name_1 = self.textEdit_3.toPlainText().strip()
        column_name_2 = self.textEdit_4.toPlainText().strip()

        if not column_name_1 or not column_name_2:
            print("错误：列名输入为空，请选择有效列名")
            return

        # 获取所有表格数据
        all_rows = self.all_table_data
        if not all_rows:
            print("错误：表格数据为空")
            return

        # 获取有效列名（c1, c2...）对应的实际列索引
        try:
            # 解析列名（假设列名格式为c1, c2等）
            col_idx1 = int(column_name_1[1:]) - 1  # 例如 c1 -> 索引0
            col_idx2 = int(column_name_2[1:]) - 1
        except (IndexError, ValueError):
            print("错误：列名格式应为c1, c2等")
            return

        # 检查列索引是否合法
        max_col = len(all_rows[0]) - 1
        if col_idx1 < 0 or col_idx1 > max_col or col_idx2 < 0 or col_idx2 > max_col:
            print("错误：列索引超出范围")
            return

        # 提取数据并转换为浮点数
        data_sample1 = []
        data_sample2 = []

        for row_idx, row in enumerate(all_rows):
            # 跳过空行
            if not row:
                continue

            # 处理第一列数据
            val1 = row[col_idx1] if col_idx1 < len(row) else None
            try:
                if val1 is not None and val1.strip():
                    data_sample1.append(float(val1))
            except ValueError:
                if row_idx == 0:  # 假设第一行可能是标题，允许跳过
                    print(f"警告：跳过第一行标题（列{column_name_1}）")
                else:
                    print(f"警告：第{row_idx + 1}行，列{column_name_1}无效数据: {val1}")

            # 处理第二列数据
            val2 = row[col_idx2] if col_idx2 < len(row) else None
            try:
                if val2 is not None and val2.strip():
                    data_sample2.append(float(val2))
            except ValueError:
                if row_idx == 0:
                    print(f"警告：跳过第一行标题（列{column_name_2}）")
                else:
                    print(f"警告：第{row_idx + 1}行，列{column_name_2}无效数据: {val2}")

        # 数据有效性检查
        if len(data_sample1) < 2 or len(data_sample2) < 2:
            print("错误：单样本有效数据不足（至少需要2个有效值）")
            print(f"样本1数量: {len(data_sample1)}, 样本2数量: {len(data_sample2)}")
            return

        # 存储数据供后续使用
        self.data_sample1 = data_sample1
        self.data_sample2 = data_sample2

        print(f"样本1数据（前10项）: {data_sample1[:10]} (总数: {len(data_sample1)})")
        print(f"样本2数据（前10项）: {data_sample2[:10]} (总数: {len(data_sample2)})")
        print("【handle_radio2_click】执行结束\n")
        # 方法 3：对应 radioButton_3 点击
    def handle_radio3_click(self):
            """汇总数据"""
            if self.radioButton_3.isChecked():
                # 执行 radioButton_3 对应的逻辑
                print("RadioButton 3 被选中")
                # 这里添加具体功能代码

        # 方法 4：确定按钮点击时调用
    def on_confirm_button_click(self):
            # 检查当前选中的 RadioButton 并调用对应方法
            if self.radioButton.isChecked():
                self.handle_radio1_click()
            elif self.radioButton_2.isChecked():
                self.handle_radio2_click()
            elif self.radioButton_3.isChecked():
                self.handle_radio3_click()
            else:
                # 处理未选中情况（可选）
                print("未选择任何 RadioButton")
            self.perform_t_test()

    def perform_t_test(self):
        """执行双样本t检验（含方差齐性检验）"""

        # 数据检查
        if not hasattr(self, 'data_sample1') or not hasattr(self, 'data_sample2'):
            debug_msg = "错误：未找到data_sample1或data_sample2属性"
            print(f"[DEBUG] {debug_msg}")
            QMessageBox.warning(self, "错误", "请先选择数据列并点击确定按钮")
            return

        try:
            # 获取参数
            assume_equal_var = self.checkBox.isChecked()
            conf_level = float(self.textEdit_6.toPlainText())
            test_diff = float(self.textEdit_5.toPlainText())
            hypothesis_relation = self.comboBox.currentText()


            # 方差齐性检验（F检验）
            var1, var2 = np.var(self.data_sample1, ddof=1), np.var(self.data_sample2, ddof=1)
            f_value = max(var1, var2) / min(var1, var2)
            dfn = len(self.data_sample1) - 1 if var1 > var2 else len(self.data_sample2) - 1
            dfd = len(self.data_sample2) - 1 if var1 > var2 else len(self.data_sample1) - 1
            f_p_value = stats.f.sf(f_value, dfn, dfd) * 2  # 双侧检验

            # 确定检验方向
            if "μ₁ < μ₂" in hypothesis_relation:
                alt_scipy = "greater"
                direction_symbol = "<"
            elif "μ₁ > μ₂" in hypothesis_relation:
                alt_scipy = "less"
                direction_symbol = ">"
            else:
                alt_scipy = "two-sided"
                direction_symbol = "≠"

            # 计算基本统计量
            n1, n2 = len(self.data_sample1), len(self.data_sample2)
            mean1, mean2 = np.mean(self.data_sample1), np.mean(self.data_sample2)

            # 根据等方差假设选择计算方法
            if assume_equal_var:
                # 合并方差t检验
                pooled_var = ((n1 - 1) * var1 + (n2 - 1) * var2) / (n1 + n2 - 2)
                std_err = np.sqrt(pooled_var * (1 / n1 + 1 / n2))
                df = n1 + n2 - 2
                pooled_std = np.sqrt(pooled_var)
            else:
                # Welch校正t检验
                std_err = np.sqrt(var1 / n1 + var2 / n2)
                df = (var1 / n1 + var2 / n2) ** 2 / ((var1 / n1) ** 2 / (n1 - 1) + (var2 / n2) ** 2 / (n2 - 1))
                pooled_std = "N/A（使用各自标准差）"

            # 计算t统计量和p值
            mean_diff = mean1 - mean2
            t_stat = (mean_diff - test_diff) / std_err

            if alt_scipy == "two-sided":
                p_value = 2 * stats.t.sf(np.abs(t_stat), df)
            else:
                p_value = stats.t.sf(t_stat, df) if alt_scipy == "greater" else stats.t.cdf(t_stat, df)

            # 置信区间计算
            t_critical = stats.t.ppf(1 - (1 - conf_level / 100) / 2, df)
            ci_lower = mean_diff - t_critical * std_err
            ci_upper = mean_diff + t_critical * std_err

            if direction_symbol == '<':
                ci_display = f"{ci_upper:.2f}"
            elif direction_symbol == '>':
                ci_display = f"{ci_lower:.2f}"
            else:
                ci_display = f"[{ci_lower:.2f}, {ci_upper:.2f}]"
            # 格式化输出
            result = (
                f"=== 方差齐性检验 ===\n"
                f"F值 = {f_value:.4f}, P值 = {f_p_value:.4f}\n"
                f"结论: {'方差齐性' if f_p_value > 0.05 else '方差不齐'}\n"
                f"使用的t检验类型: {'合并方差t检验' if assume_equal_var else 'Welch t检验'}\n\n"
                f"=== t检验结果 ===\n"
                f"差值 = mu (C1) - mu (C2)\n"
                f"差值估计: {mean_diff:.2f}\n"
                f"差值的 {conf_level}% 置信{'上限' if direction_symbol == '<' else '下限' if direction_symbol == '>' else '区间'}: {ci_display}\n"
                f"差值 = {test_diff} (与 {direction_symbol}) 的 T 检验: "
                f"T 值 = {t_stat:.2f} P 值 = {p_value:.3f} 自由度 = {df}\n"
                f"两者标准差: C1 = {np.std(self.data_sample1, ddof=1):.4f}, C2 = {np.std(self.data_sample2, ddof=1):.4f}\n"
                f"{'合并标准差 = ' + f'{pooled_std:.4f}' if assume_equal_var else '未合并标准差（Welch检验）'}\n"
                f"样本量: C1 = {n1}, C2 = {n2}"
            )

            #print("\n" + "=" * 50)
            #print(result)
            # print("=" * 50 + "\n")
            self.main_window.display_text(result)
        except Exception as e:
            debug_msg = f"计算过程中发生错误: {str(e)}"
            print(f"[DEBUG] {debug_msg}")
            QMessageBox.critical(self, "错误", debug_msg)
            return
